// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: svrtools/v1/audit.proto

package svrtoolsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OrganisationId string                 `protobuf:"bytes,2,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	ActorId        string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Action         string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	TargetType     string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId       string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Result         string                 `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_svrtools_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditEvent) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AuditEvent) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type WriteAuditEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AuditEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAuditEventRequest) Reset() {
	*x = WriteAuditEventRequest{}
	mi := &file_svrtools_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAuditEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAuditEventRequest) ProtoMessage() {}

func (x *WriteAuditEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAuditEventRequest.ProtoReflect.Descriptor instead.
func (*WriteAuditEventRequest) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *WriteAuditEventRequest) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type WriteAuditEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAuditEventResponse) Reset() {
	*x = WriteAuditEventResponse{}
	mi := &file_svrtools_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAuditEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAuditEventResponse) ProtoMessage() {}

func (x *WriteAuditEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAuditEventResponse.ProtoReflect.Descriptor instead.
func (*WriteAuditEventResponse) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *WriteAuditEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_svrtools_v1_audit_proto protoreflect.FileDescriptor

const file_svrtools_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x17svrtools/v1/audit.proto\x12\vsvrtools.v1\"\xfe\x01\n" +
	"\n" +
	"AuditEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0forganisation_id\x18\x02 \x01(\tR\x0eorganisationId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJson\"G\n" +
	"\x16WriteAuditEventRequest\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.svrtools.v1.AuditEventR\x05event\"4\n" +
	"\x17WriteAuditEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId2l\n" +
	"\fAuditservice\x12\\\n" +
	"\x0fWriteAuditEvent\x12#.svrtools.v1.WriteAuditEventRequest\x1a$.svrtools.v1.WriteAuditEventResponseBDZBgithub.com/pgd1001/svrtools/packages/sdk-go/svrtools/v1;svrtoolsv1b\x06proto3"

var (
	file_svrtools_v1_audit_proto_rawDescOnce sync.Once
	file_svrtools_v1_audit_proto_rawDescData []byte
)

func file_svrtools_v1_audit_proto_rawDescGZIP() []byte {
	file_svrtools_v1_audit_proto_rawDescOnce.Do(func() {
		file_svrtools_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svrtools_v1_audit_proto_rawDesc), len(file_svrtools_v1_audit_proto_rawDesc)))
	})
	return file_svrtools_v1_audit_proto_rawDescData
}

var file_svrtools_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_svrtools_v1_audit_proto_goTypes = []any{
	(*AuditEvent)(nil),              // 0: svrtools.v1.AuditEvent
	(*WriteAuditEventRequest)(nil),  // 1: svrtools.v1.WriteAuditEventRequest
	(*WriteAuditEventResponse)(nil), // 2: svrtools.v1.WriteAuditEventResponse
}
var file_svrtools_v1_audit_proto_depIdxs = []int32{
	0, // 0: svrtools.v1.WriteAuditEventRequest.event:type_name -> svrtools.v1.AuditEvent
	1, // 1: svrtools.v1.Auditservice.WriteAuditEvent:input_type -> svrtools.v1.WriteAuditEventRequest
	2, // 2: svrtools.v1.Auditservice.WriteAuditEvent:output_type -> svrtools.v1.WriteAuditEventResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_svrtools_v1_audit_proto_init() }
func file_svrtools_v1_audit_proto_init() {
	if File_svrtools_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svrtools_v1_audit_proto_rawDesc), len(file_svrtools_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svrtools_v1_audit_proto_goTypes,
		DependencyIndexes: file_svrtools_v1_audit_proto_depIdxs,
		MessageInfos:      file_svrtools_v1_audit_proto_msgTypes,
	}.Build()
	File_svrtools_v1_audit_proto = out.File
	file_svrtools_v1_audit_proto_goTypes = nil
	file_svrtools_v1_audit_proto_depIdxs = nil
}
