// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: svrtools/v1/execution.proto

package svrtoolsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_QUEUED      ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_RUNNING     ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_SUCCEEDED   ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 4
	ExecutionStatus_EXECUTION_STATUS_DENIED      ExecutionStatus = 5
	ExecutionStatus_EXECUTION_STATUS_CANCELLED   ExecutionStatus = 6
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_QUEUED",
		2: "EXECUTION_STATUS_RUNNING",
		3: "EXECUTION_STATUS_SUCCEEDED",
		4: "EXECUTION_STATUS_FAILED",
		5: "EXECUTION_STATUS_DENIED",
		6: "EXECUTION_STATUS_CANCELLED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_QUEUED":      1,
		"EXECUTION_STATUS_RUNNING":     2,
		"EXECUTION_STATUS_SUCCEEDED":   3,
		"EXECUTION_STATUS_FAILED":      4,
		"EXECUTION_STATUS_DENIED":      5,
		"EXECUTION_STATUS_CANCELLED":   6,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_svrtools_v1_execution_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_svrtools_v1_execution_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_svrtools_v1_execution_proto_rawDescGZIP(), []int{0}
}

type CreateExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExecutionRequest) Reset() {
	*x = CreateExecutionRequest{}
	mi := &file_svrtools_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutionRequest) ProtoMessage() {}

func (x *CreateExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutionRequest.ProtoReflect.Descriptor instead.
func (*CreateExecutionRequest) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExecutionRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CreateExecutionRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateExecutionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateExecutionRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type CreateExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=svrtools.v1.ExecutionStatus" json:"status,omitempty"`
	StatusMessage string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExecutionResponse) Reset() {
	*x = CreateExecutionResponse{}
	mi := &file_svrtools_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutionResponse) ProtoMessage() {}

func (x *CreateExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutionResponse.ProtoReflect.Descriptor instead.
func (*CreateExecutionResponse) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExecutionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CreateExecutionResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *CreateExecutionResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_svrtools_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ExecutionId   string                   `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        ExecutionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=svrtools.v1.ExecutionStatus" json:"status,omitempty"`
	Command       string                   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	ActorId       string                   `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Results       []*ExecutionTargetResult `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionResponse) Reset() {
	*x = GetExecutionResponse{}
	mi := &file_svrtools_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionResponse) ProtoMessage() {}

func (x *GetExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionResponse) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *GetExecutionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetExecutionResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *GetExecutionResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetExecutionResponse) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *GetExecutionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetExecutionResponse) GetResults() []*ExecutionTargetResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type StreamExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExecutionRequest) Reset() {
	*x = StreamExecutionRequest{}
	mi := &file_svrtools_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecutionRequest) ProtoMessage() {}

func (x *StreamExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExecutionRequest.ProtoReflect.Descriptor instead.
func (*StreamExecutionRequest) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *StreamExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=svrtools.v1.ExecutionStatus" json:"status,omitempty"`
	TargetResult  *ExecutionTargetResult `protobuf:"bytes,3,opt,name=target_result,json=targetResult,proto3,oneof" json:"target_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_svrtools_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionEvent) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ExecutionEvent) GetTargetResult() *ExecutionTargetResult {
	if x != nil {
		return x.TargetResult
	}
	return nil
}

type ExecutionTargetResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionTargetResult) Reset() {
	*x = ExecutionTargetResult{}
	mi := &file_svrtools_v1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTargetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTargetResult) ProtoMessage() {}

func (x *ExecutionTargetResult) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTargetResult.ProtoReflect.Descriptor instead.
func (*ExecutionTargetResult) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionTargetResult) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ExecutionTargetResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutionTargetResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecutionTargetResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecutionTargetResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecutionTargetResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_svrtools_v1_execution_proto protoreflect.FileDescriptor

const file_svrtools_v1_execution_proto_rawDesc = "" +
	"\n" +
	"\x1bsvrtools/v1/execution.proto\x12\vsvrtools.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"{\n" +
	"\x16CreateExecutionRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"\x99\x01\n" +
	"\x17CreateExecutionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.svrtools.v1.ExecutionStatusR\x06status\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\"8\n" +
	"\x13GetExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\x9d\x02\n" +
	"\x14GetExecutionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.svrtools.v1.ExecutionStatusR\x06status\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\aresults\x18\x06 \x03(\v2\".svrtools.v1.ExecutionTargetResultR\aresults\";\n" +
	"\x16StreamExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xc9\x01\n" +
	"\x0eExecutionEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.svrtools.v1.ExecutionStatusR\x06status\x12L\n" +
	"\rtarget_result\x18\x03 \x01(\v2\".svrtools.v1.ExecutionTargetResultH\x00R\ftargetResult\x88\x01\x01B\x10\n" +
	"\x0e_target_result\"\xb8\x01\n" +
	"\x15ExecutionTargetResult\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs*\xe8\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EXECUTION_STATUS_QUEUED\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_SUCCEEDED\x10\x03\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17EXECUTION_STATUS_DENIED\x10\x05\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_CANCELLED\x10\x062\x9c\x02\n" +
	"\x10ExecutionService\x12\\\n" +
	"\x0fCreateExecution\x12#.svrtools.v1.CreateExecutionRequest\x1a$.svrtools.v1.CreateExecutionResponse\x12S\n" +
	"\fGetExecution\x12 .svrtools.v1.GetExecutionRequest\x1a!.svrtools.v1.GetExecutionResponse\x12U\n" +
	"\x0fStreamExecution\x12#.svrtools.v1.StreamExecutionRequest\x1a\x1b.svrtools.v1.ExecutionEvent0\x01BDZBgithub.com/pgd1001/svrtools/packages/sdk-go/svrtools/v1;svrtoolsv1b\x06proto3"

var (
	file_svrtools_v1_execution_proto_rawDescOnce sync.Once
	file_svrtools_v1_execution_proto_rawDescData []byte
)

func file_svrtools_v1_execution_proto_rawDescGZIP() []byte {
	file_svrtools_v1_execution_proto_rawDescOnce.Do(func() {
		file_svrtools_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svrtools_v1_execution_proto_rawDesc), len(file_svrtools_v1_execution_proto_rawDesc)))
	})
	return file_svrtools_v1_execution_proto_rawDescData
}

var file_svrtools_v1_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svrtools_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_svrtools_v1_execution_proto_goTypes = []any{
	(ExecutionStatus)(0),            // 0: svrtools.v1.ExecutionStatus
	(*CreateExecutionRequest)(nil),  // 1: svrtools.v1.CreateExecutionRequest
	(*CreateExecutionResponse)(nil), // 2: svrtools.v1.CreateExecutionResponse
	(*GetExecutionRequest)(nil),     // 3: svrtools.v1.GetExecutionRequest
	(*GetExecutionResponse)(nil),    // 4: svrtools.v1.GetExecutionResponse
	(*StreamExecutionRequest)(nil),  // 5: svrtools.v1.StreamExecutionRequest
	(*ExecutionEvent)(nil),          // 6: svrtools.v1.ExecutionEvent
	(*ExecutionTargetResult)(nil),   // 7: svrtools.v1.ExecutionTargetResult
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_svrtools_v1_execution_proto_depIdxs = []int32{
	0, // 0: svrtools.v1.CreateExecutionResponse.status:type_name -> svrtools.v1.ExecutionStatus
	0, // 1: svrtools.v1.GetExecutionResponse.status:type_name -> svrtools.v1.ExecutionStatus
	8, // 2: svrtools.v1.GetExecutionResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: svrtools.v1.GetExecutionResponse.results:type_name -> svrtools.v1.ExecutionTargetResult
	0, // 4: svrtools.v1.ExecutionEvent.status:type_name -> svrtools.v1.ExecutionStatus
	7, // 5: svrtools.v1.ExecutionEvent.target_result:type_name -> svrtools.v1.ExecutionTargetResult
	1, // 6: svrtools.v1.ExecutionService.CreateExecution:input_type -> svrtools.v1.CreateExecutionRequest
	3, // 7: svrtools.v1.ExecutionService.GetExecution:input_type -> svrtools.v1.GetExecutionRequest
	5, // 8: svrtools.v1.ExecutionService.StreamExecution:input_type -> svrtools.v1.StreamExecutionRequest
	2, // 9: svrtools.v1.ExecutionService.CreateExecution:output_type -> svrtools.v1.CreateExecutionResponse
	4, // 10: svrtools.v1.ExecutionService.GetExecution:output_type -> svrtools.v1.GetExecutionResponse
	6, // 11: svrtools.v1.ExecutionService.StreamExecution:output_type -> svrtools.v1.ExecutionEvent
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_svrtools_v1_execution_proto_init() }
func file_svrtools_v1_execution_proto_init() {
	if File_svrtools_v1_execution_proto != nil {
		return
	}
	file_svrtools_v1_execution_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svrtools_v1_execution_proto_rawDesc), len(file_svrtools_v1_execution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svrtools_v1_execution_proto_goTypes,
		DependencyIndexes: file_svrtools_v1_execution_proto_depIdxs,
		EnumInfos:         file_svrtools_v1_execution_proto_enumTypes,
		MessageInfos:      file_svrtools_v1_execution_proto_msgTypes,
	}.Build()
	File_svrtools_v1_execution_proto = out.File
	file_svrtools_v1_execution_proto_goTypes = nil
	file_svrtools_v1_execution_proto_depIdxs = nil
}
