// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: svrtools/v1/health.proto

package svrtoolsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_svrtools_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_health_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_svrtools_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_svrtools_v1_health_proto protoreflect.FileDescriptor

const file_svrtools_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x18svrtools/v1/health.proto\x12\vsvrtools.v1\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2[\n" +
	"\rHealthService\x12J\n" +
	"\x05Check\x12\x1f.svrtools.v1.HealthCheckRequest\x1a .svrtools.v1.HealthCheckResponseBDZBgithub.com/pgd1001/svrtools/packages/sdk-go/svrtools/v1;svrtoolsv1b\x06proto3"

var (
	file_svrtools_v1_health_proto_rawDescOnce sync.Once
	file_svrtools_v1_health_proto_rawDescData []byte
)

func file_svrtools_v1_health_proto_rawDescGZIP() []byte {
	file_svrtools_v1_health_proto_rawDescOnce.Do(func() {
		file_svrtools_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svrtools_v1_health_proto_rawDesc), len(file_svrtools_v1_health_proto_rawDesc)))
	})
	return file_svrtools_v1_health_proto_rawDescData
}

var file_svrtools_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_svrtools_v1_health_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: svrtools.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: svrtools.v1.HealthCheckResponse
}
var file_svrtools_v1_health_proto_depIdxs = []int32{
	0, // 0: svrtools.v1.HealthService.Check:input_type -> svrtools.v1.HealthCheckRequest
	1, // 1: svrtools.v1.HealthService.Check:output_type -> svrtools.v1.HealthCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svrtools_v1_health_proto_init() }
func file_svrtools_v1_health_proto_init() {
	if File_svrtools_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svrtools_v1_health_proto_rawDesc), len(file_svrtools_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svrtools_v1_health_proto_goTypes,
		DependencyIndexes: file_svrtools_v1_health_proto_depIdxs,
		MessageInfos:      file_svrtools_v1_health_proto_msgTypes,
	}.Build()
	File_svrtools_v1_health_proto = out.File
	file_svrtools_v1_health_proto_goTypes = nil
	file_svrtools_v1_health_proto_depIdxs = nil
}
