// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: svrtools/v1/server.proto

package svrtoolsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_svrtools_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Server) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Server) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Server) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Server) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	TagKey        string                 `protobuf:"bytes,2,opt,name=tag_key,json=tagKey,proto3" json:"tag_key,omitempty"`
	TagValue      string                 `protobuf:"bytes,3,opt,name=tag_value,json=tagValue,proto3" json:"tag_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_svrtools_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *ListServersRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ListServersRequest) GetTagKey() string {
	if x != nil {
		return x.TagKey
	}
	return ""
}

func (x *ListServersRequest) GetTagValue() string {
	if x != nil {
		return x.TagValue
	}
	return ""
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_svrtools_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *ListServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_svrtools_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerResponse) Reset() {
	*x = GetServerResponse{}
	mi := &file_svrtools_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResponse) ProtoMessage() {}

func (x *GetServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svrtools_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResponse.ProtoReflect.Descriptor instead.
func (*GetServerResponse) Descriptor() ([]byte, []int) {
	return file_svrtools_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

var File_svrtools_v1_server_proto protoreflect.FileDescriptor

const file_svrtools_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x18svrtools/v1/server.proto\x12\vsvrtools.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x02\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x121\n" +
	"\x04tags\x18\x05 \x03(\v2\x1d.svrtools.v1.Server.TagsEntryR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12<\n" +
	"\flast_seen_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x12ListServersRequest\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12\x17\n" +
	"\atag_key\x18\x02 \x01(\tR\x06tagKey\x12\x1b\n" +
	"\ttag_value\x18\x03 \x01(\tR\btagValue\"D\n" +
	"\x13ListServersResponse\x12-\n" +
	"\aservers\x18\x01 \x03(\v2\x13.svrtools.v1.ServerR\aservers\"/\n" +
	"\x10GetServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"@\n" +
	"\x11GetServerResponse\x12+\n" +
	"\x06server\x18\x01 \x01(\v2\x13.svrtools.v1.ServerR\x06server2\xad\x01\n" +
	"\rServerService\x12P\n" +
	"\vListServers\x12\x1f.svrtools.v1.ListServersRequest\x1a .svrtools.v1.ListServersResponse\x12J\n" +
	"\tGetServer\x12\x1d.svrtools.v1.GetServerRequest\x1a\x1e.svrtools.v1.GetServerResponseBDZBgithub.com/pgd1001/svrtools/packages/sdk-go/svrtools/v1;svrtoolsv1b\x06proto3"

var (
	file_svrtools_v1_server_proto_rawDescOnce sync.Once
	file_svrtools_v1_server_proto_rawDescData []byte
)

func file_svrtools_v1_server_proto_rawDescGZIP() []byte {
	file_svrtools_v1_server_proto_rawDescOnce.Do(func() {
		file_svrtools_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svrtools_v1_server_proto_rawDesc), len(file_svrtools_v1_server_proto_rawDesc)))
	})
	return file_svrtools_v1_server_proto_rawDescData
}

var file_svrtools_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_svrtools_v1_server_proto_goTypes = []any{
	(*Server)(nil),                // 0: svrtools.v1.Server
	(*ListServersRequest)(nil),    // 1: svrtools.v1.ListServersRequest
	(*ListServersResponse)(nil),   // 2: svrtools.v1.ListServersResponse
	(*GetServerRequest)(nil),      // 3: svrtools.v1.GetServerRequest
	(*GetServerResponse)(nil),     // 4: svrtools.v1.GetServerResponse
	nil,                           // 5: svrtools.v1.Server.TagsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_svrtools_v1_server_proto_depIdxs = []int32{
	5, // 0: svrtools.v1.Server.tags:type_name -> svrtools.v1.Server.TagsEntry
	6, // 1: svrtools.v1.Server.last_seen_at:type_name -> google.protobuf.Timestamp
	0, // 2: svrtools.v1.ListServersResponse.servers:type_name -> svrtools.v1.Server
	0, // 3: svrtools.v1.GetServerResponse.server:type_name -> svrtools.v1.Server
	1, // 4: svrtools.v1.ServerService.ListServers:input_type -> svrtools.v1.ListServersRequest
	3, // 5: svrtools.v1.ServerService.GetServer:input_type -> svrtools.v1.GetServerRequest
	2, // 6: svrtools.v1.ServerService.ListServers:output_type -> svrtools.v1.ListServersResponse
	4, // 7: svrtools.v1.ServerService.GetServer:output_type -> svrtools.v1.GetServerResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_svrtools_v1_server_proto_init() }
func file_svrtools_v1_server_proto_init() {
	if File_svrtools_v1_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svrtools_v1_server_proto_rawDesc), len(file_svrtools_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svrtools_v1_server_proto_goTypes,
		DependencyIndexes: file_svrtools_v1_server_proto_depIdxs,
		MessageInfos:      file_svrtools_v1_server_proto_msgTypes,
	}.Build()
	File_svrtools_v1_server_proto = out.File
	file_svrtools_v1_server_proto_goTypes = nil
	file_svrtools_v1_server_proto_depIdxs = nil
}
