// Package sshcreds resolves the SSH credential for one target on the runner.
//
// The control plane deliberately never sees private key material. It stores
// only a reference, and each runner holds the material for the hosts it is
// scoped to. That split means a compromise of the API database yields no
// ability to log in to customer machines, and it is why this package lives in
// the runner's trust domain rather than behind an API call.
package sshcreds

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/pgd1001/svrtools/packages/sshx"
)

// ErrUnknownReference reports that the keystore holds nothing for the
// requested reference. The runner treats this as a target failure rather than
// falling back to another credential, because silently using a different
// identity than the one the control plane recorded would break the audit
// trail.
var ErrUnknownReference = errors.New("no ssh credential is configured for this reference")

// ErrInvalidReference reports a reference that could not be part of a
// filename. References come from the API, so they are validated before being
// joined to a path rather than trusted.
var ErrInvalidReference = errors.New("ssh credential reference is not a valid name")

// Keystore resolves credential references against a directory on the runner
// host.
//
// The layout is one file per reference:
//
//	<dir>/<reference>            PEM-encoded private key
//	<dir>/<reference>.passphrase optional passphrase for that key
//	<dir>/<reference>.password   optional password, for hosts without key auth
//
// A plain directory is used rather than an embedded secret format because it
// composes with the tools operators already have: systemd credentials, mounted
// secrets, and file permissions all apply without this package inventing its
// own access model.
type Keystore struct {
	dir string
}

// NewKeystore returns a keystore backed by dir. An empty dir yields a
// keystore that resolves nothing, which lets a runner start in simulate mode
// without credentials while still failing closed on a real job.
func NewKeystore(dir string) *Keystore {
	return &Keystore{dir: strings.TrimSpace(dir)}
}

// Configured reports whether a directory was supplied.
func (k *Keystore) Configured() bool {
	return k != nil && k.dir != ""
}

// validReference rejects anything that could escape the keystore directory or
// name a file the operator did not intend. Only a conservative character set
// is allowed, since references are generated by the product rather than typed
// freely.
func validReference(reference string) bool {
	if reference == "" || len(reference) > 128 {
		return false
	}
	if reference != filepath.Base(reference) {
		return false
	}
	if strings.HasPrefix(reference, ".") {
		return false
	}
	for _, r := range reference {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case r == '-', r == '_':
		default:
			return false
		}
	}
	return true
}

// Resolve returns the credential for reference.
func (k *Keystore) Resolve(reference string) (sshx.Credential, error) {
	if !k.Configured() {
		return sshx.Credential{}, ErrUnknownReference
	}
	if !validReference(reference) {
		return sshx.Credential{}, fmt.Errorf("%w: %q", ErrInvalidReference, reference)
	}

	base := filepath.Join(k.dir, reference)
	var credential sshx.Credential

	key, err := os.ReadFile(base)
	switch {
	case err == nil:
		credential.PrivateKey = key
	case !errors.Is(err, os.ErrNotExist):
		return sshx.Credential{}, fmt.Errorf("read ssh key for %s: %w", reference, err)
	}

	if len(credential.PrivateKey) > 0 {
		passphrase, err := os.ReadFile(base + ".passphrase")
		switch {
		case err == nil:
			credential.Passphrase = trimSecret(passphrase)
		case !errors.Is(err, os.ErrNotExist):
			return sshx.Credential{}, fmt.Errorf("read ssh passphrase for %s: %w", reference, err)
		}
	}

	password, err := os.ReadFile(base + ".password")
	switch {
	case err == nil:
		credential.Password = string(trimSecret(password))
	case !errors.Is(err, os.ErrNotExist):
		return sshx.Credential{}, fmt.Errorf("read ssh password for %s: %w", reference, err)
	}

	if len(credential.PrivateKey) == 0 && credential.Password == "" {
		return sshx.Credential{}, fmt.Errorf("%w: %s", ErrUnknownReference, reference)
	}
	return credential, nil
}

// trimSecret removes the trailing newline an editor or `echo` leaves behind,
// which would otherwise be treated as part of the secret.
func trimSecret(value []byte) []byte {
	return []byte(strings.TrimRight(string(value), "\r\n"))
}
