// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: svrtools/v1/execution.proto

package svrtoolsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pgd1001/svrtools/packages/sdk-go/svrtools/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExecutionServiceName is the fully-qualified name of the ExecutionService service.
	ExecutionServiceName = "svrtools.v1.ExecutionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExecutionServiceCreateExecutionProcedure is the fully-qualified name of the ExecutionService's
	// CreateExecution RPC.
	ExecutionServiceCreateExecutionProcedure = "/svrtools.v1.ExecutionService/CreateExecution"
	// ExecutionServiceGetExecutionProcedure is the fully-qualified name of the ExecutionService's
	// GetExecution RPC.
	ExecutionServiceGetExecutionProcedure = "/svrtools.v1.ExecutionService/GetExecution"
	// ExecutionServiceStreamExecutionProcedure is the fully-qualified name of the ExecutionService's
	// StreamExecution RPC.
	ExecutionServiceStreamExecutionProcedure = "/svrtools.v1.ExecutionService/StreamExecution"
)

// ExecutionServiceClient is a client for the svrtools.v1.ExecutionService service.
type ExecutionServiceClient interface {
	CreateExecution(context.Context, *connect.Request[v1.CreateExecutionRequest]) (*connect.Response[v1.CreateExecutionResponse], error)
	GetExecution(context.Context, *connect.Request[v1.GetExecutionRequest]) (*connect.Response[v1.GetExecutionResponse], error)
	StreamExecution(context.Context, *connect.Request[v1.StreamExecutionRequest]) (*connect.ServerStreamForClient[v1.ExecutionEvent], error)
}

// NewExecutionServiceClient constructs a client for the svrtools.v1.ExecutionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExecutionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExecutionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	executionServiceMethods := v1.File_svrtools_v1_execution_proto.Services().ByName("ExecutionService").Methods()
	return &executionServiceClient{
		createExecution: connect.NewClient[v1.CreateExecutionRequest, v1.CreateExecutionResponse](
			httpClient,
			baseURL+ExecutionServiceCreateExecutionProcedure,
			connect.WithSchema(executionServiceMethods.ByName("CreateExecution")),
			connect.WithClientOptions(opts...),
		),
		getExecution: connect.NewClient[v1.GetExecutionRequest, v1.GetExecutionResponse](
			httpClient,
			baseURL+ExecutionServiceGetExecutionProcedure,
			connect.WithSchema(executionServiceMethods.ByName("GetExecution")),
			connect.WithClientOptions(opts...),
		),
		streamExecution: connect.NewClient[v1.StreamExecutionRequest, v1.ExecutionEvent](
			httpClient,
			baseURL+ExecutionServiceStreamExecutionProcedure,
			connect.WithSchema(executionServiceMethods.ByName("StreamExecution")),
			connect.WithClientOptions(opts...),
		),
	}
}

// executionServiceClient implements ExecutionServiceClient.
type executionServiceClient struct {
	createExecution *connect.Client[v1.CreateExecutionRequest, v1.CreateExecutionResponse]
	getExecution    *connect.Client[v1.GetExecutionRequest, v1.GetExecutionResponse]
	streamExecution *connect.Client[v1.StreamExecutionRequest, v1.ExecutionEvent]
}

// CreateExecution calls svrtools.v1.ExecutionService.CreateExecution.
func (c *executionServiceClient) CreateExecution(ctx context.Context, req *connect.Request[v1.CreateExecutionRequest]) (*connect.Response[v1.CreateExecutionResponse], error) {
	return c.createExecution.CallUnary(ctx, req)
}

// GetExecution calls svrtools.v1.ExecutionService.GetExecution.
func (c *executionServiceClient) GetExecution(ctx context.Context, req *connect.Request[v1.GetExecutionRequest]) (*connect.Response[v1.GetExecutionResponse], error) {
	return c.getExecution.CallUnary(ctx, req)
}

// StreamExecution calls svrtools.v1.ExecutionService.StreamExecution.
func (c *executionServiceClient) StreamExecution(ctx context.Context, req *connect.Request[v1.StreamExecutionRequest]) (*connect.ServerStreamForClient[v1.ExecutionEvent], error) {
	return c.streamExecution.CallServerStream(ctx, req)
}

// ExecutionServiceHandler is an implementation of the svrtools.v1.ExecutionService service.
type ExecutionServiceHandler interface {
	CreateExecution(context.Context, *connect.Request[v1.CreateExecutionRequest]) (*connect.Response[v1.CreateExecutionResponse], error)
	GetExecution(context.Context, *connect.Request[v1.GetExecutionRequest]) (*connect.Response[v1.GetExecutionResponse], error)
	StreamExecution(context.Context, *connect.Request[v1.StreamExecutionRequest], *connect.ServerStream[v1.ExecutionEvent]) error
}

// NewExecutionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExecutionServiceHandler(svc ExecutionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	executionServiceMethods := v1.File_svrtools_v1_execution_proto.Services().ByName("ExecutionService").Methods()
	executionServiceCreateExecutionHandler := connect.NewUnaryHandler(
		ExecutionServiceCreateExecutionProcedure,
		svc.CreateExecution,
		connect.WithSchema(executionServiceMethods.ByName("CreateExecution")),
		connect.WithHandlerOptions(opts...),
	)
	executionServiceGetExecutionHandler := connect.NewUnaryHandler(
		ExecutionServiceGetExecutionProcedure,
		svc.GetExecution,
		connect.WithSchema(executionServiceMethods.ByName("GetExecution")),
		connect.WithHandlerOptions(opts...),
	)
	executionServiceStreamExecutionHandler := connect.NewServerStreamHandler(
		ExecutionServiceStreamExecutionProcedure,
		svc.StreamExecution,
		connect.WithSchema(executionServiceMethods.ByName("StreamExecution")),
		connect.WithHandlerOptions(opts...),
	)
	return "/svrtools.v1.ExecutionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExecutionServiceCreateExecutionProcedure:
			executionServiceCreateExecutionHandler.ServeHTTP(w, r)
		case ExecutionServiceGetExecutionProcedure:
			executionServiceGetExecutionHandler.ServeHTTP(w, r)
		case ExecutionServiceStreamExecutionProcedure:
			executionServiceStreamExecutionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExecutionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExecutionServiceHandler struct{}

func (UnimplementedExecutionServiceHandler) CreateExecution(context.Context, *connect.Request[v1.CreateExecutionRequest]) (*connect.Response[v1.CreateExecutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("svrtools.v1.ExecutionService.CreateExecution is not implemented"))
}

func (UnimplementedExecutionServiceHandler) GetExecution(context.Context, *connect.Request[v1.GetExecutionRequest]) (*connect.Response[v1.GetExecutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("svrtools.v1.ExecutionService.GetExecution is not implemented"))
}

func (UnimplementedExecutionServiceHandler) StreamExecution(context.Context, *connect.Request[v1.StreamExecutionRequest], *connect.ServerStream[v1.ExecutionEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("svrtools.v1.ExecutionService.StreamExecution is not implemented"))
}
