// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: svrtools/v1/server.proto

package svrtoolsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pgd1001/svrtools/packages/sdk-go/svrtools/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServerServiceName is the fully-qualified name of the ServerService service.
	ServerServiceName = "svrtools.v1.ServerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServerServiceListServersProcedure is the fully-qualified name of the ServerService's ListServers
	// RPC.
	ServerServiceListServersProcedure = "/svrtools.v1.ServerService/ListServers"
	// ServerServiceGetServerProcedure is the fully-qualified name of the ServerService's GetServer RPC.
	ServerServiceGetServerProcedure = "/svrtools.v1.ServerService/GetServer"
)

// ServerServiceClient is a client for the svrtools.v1.ServerService service.
type ServerServiceClient interface {
	ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error)
	GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error)
}

// NewServerServiceClient constructs a client for the svrtools.v1.ServerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serverServiceMethods := v1.File_svrtools_v1_server_proto.Services().ByName("ServerService").Methods()
	return &serverServiceClient{
		listServers: connect.NewClient[v1.ListServersRequest, v1.ListServersResponse](
			httpClient,
			baseURL+ServerServiceListServersProcedure,
			connect.WithSchema(serverServiceMethods.ByName("ListServers")),
			connect.WithClientOptions(opts...),
		),
		getServer: connect.NewClient[v1.GetServerRequest, v1.GetServerResponse](
			httpClient,
			baseURL+ServerServiceGetServerProcedure,
			connect.WithSchema(serverServiceMethods.ByName("GetServer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serverServiceClient implements ServerServiceClient.
type serverServiceClient struct {
	listServers *connect.Client[v1.ListServersRequest, v1.ListServersResponse]
	getServer   *connect.Client[v1.GetServerRequest, v1.GetServerResponse]
}

// ListServers calls svrtools.v1.ServerService.ListServers.
func (c *serverServiceClient) ListServers(ctx context.Context, req *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error) {
	return c.listServers.CallUnary(ctx, req)
}

// GetServer calls svrtools.v1.ServerService.GetServer.
func (c *serverServiceClient) GetServer(ctx context.Context, req *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error) {
	return c.getServer.CallUnary(ctx, req)
}

// ServerServiceHandler is an implementation of the svrtools.v1.ServerService service.
type ServerServiceHandler interface {
	ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error)
	GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error)
}

// NewServerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServerServiceHandler(svc ServerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serverServiceMethods := v1.File_svrtools_v1_server_proto.Services().ByName("ServerService").Methods()
	serverServiceListServersHandler := connect.NewUnaryHandler(
		ServerServiceListServersProcedure,
		svc.ListServers,
		connect.WithSchema(serverServiceMethods.ByName("ListServers")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceGetServerHandler := connect.NewUnaryHandler(
		ServerServiceGetServerProcedure,
		svc.GetServer,
		connect.WithSchema(serverServiceMethods.ByName("GetServer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/svrtools.v1.ServerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServerServiceListServersProcedure:
			serverServiceListServersHandler.ServeHTTP(w, r)
		case ServerServiceGetServerProcedure:
			serverServiceGetServerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServerServiceHandler struct{}

func (UnimplementedServerServiceHandler) ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("svrtools.v1.ServerService.ListServers is not implemented"))
}

func (UnimplementedServerServiceHandler) GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("svrtools.v1.ServerService.GetServer is not implemented"))
}
